### ISSUE TITLE
Add to calendar link

### ISSUE THREAD

**Issue by ThomastheBicyclist** [freecodecamp-fresnoca/landing-page#5]
Should work for
- iCal
- Google Calendar
- Yahoo
- Outlook

**Comment by ThomastheBicyclist** [comment]
[This](https://www.npmjs.com/package/ics) looks like it could help.

**Comment by michaelachrisco** [comment]
Took a stab at this one at our meetup. Used the Meetup API and pushed it to the button as a quick talking point. Hope you dont mind @JuanPacheco2345!
